version: '2'
services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx/sites-enabled/:/etc/nginx/conf.d
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/random_walker.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    volumes_from:
      - random_walker
    links:
      - random_walker:random_walker
  random_walker:
    restart: always
    image: mkao006/random_walker:latest
    expose:
      - "8000"
    tty: true
    depends_on:
      - postgis
  postgis:
    restart: always
    image: mdillon/postgis
    volumes:
      - ./postgis/init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"